server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:5173"
              - "http://localhost:4200"
              - "http://192.168.1.15:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

      routes:
        - id: ingestion-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/documents/**, /api/v1/workspaces/**

        - id: query-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/qa/**


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

  instance:
    prefer-ip-address: true


# zipkin
management:
  tracing:
    sampling:
      probability: 1.0 # 🔥 1.0 ka matlab hai 100% requests ko trace karo (Production me ise 0.1 ya kam rakhte hain)
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans # Zipkin ka address

# Logs mein Trace ID aur Span ID dikhane ke liye pattern set karna padta hai
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"