server:
  port: 8081

spring:
  application:
    name: ingestion-service

  # Postgresql configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/document_qa
    username: admin
    password: admin12345
    driver-class-name: org.postgresql.Driver

  # JPA configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Kafka Producer Configuration
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    topic:
      ingestion: document-ingestion-topic

  # Multipart (File upload) Configuration
  servlet:
    multipart:
      max-file-size: 10MB # Ek baar me 10MB se badi PDF allow nahi karenge
      max-request-size: 10MB

# Custom MinIO Configuration
minio:
  url: http://localhost:9000
  access-key: admin
  secret-key: admin12345
  bucket-name: raw-document

# resilience4j configuration
resilience4j:
  circuitbreaker:
    instances:
      kafkaBreaker:
        sliding-window-size: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        permitted-number-of-calls-in-half-open-state: 2



eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


# zipkin
management:
  tracing:
    sampling:
      probability: 1.0 # 🔥 1.0 ka matlab hai 100% requests ko trace karo (Production me ise 0.1 ya kam rakhte hain)
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans # Zipkin ka address

# Logs mein Trace ID aur Span ID dikhane ke liye pattern set karna padta hai
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
