server:
  port: 8083

spring:
  application:
    name: query-service

  datasource:
    url: jdbc:postgresql://localhost:5433/document_worker_db
    username: admin
    password: admin12345

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  ai:
    google:
      genai:
        api-key: ${GEMINI_API_KEY}
        chat:
          options:
            model: gemini-2.5-flash

        embedding:
          api-key: ${GEMINI_API_KEY}
          options:
            model: text-embedding-004

    # groq API
    openai:
      api-key: ${GROQ_API_KEY}
      base-url: https://api.groq.com/openai
      chat:
        options:
          model: llama-3.1-8b-instant
      embedding:
        enabled: false


    vectorstore:
      pgvector:
        dimensions: 3072
        initialize-schema: false
        index-type: NONE
        distance-type: COSINE_DISTANCE

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


# zipkin
management:
  tracing:
    sampling:
      probability: 1.0 # 🔥 1.0 ka matlab hai 100% requests ko trace karo (Production me ise 0.1 ya kam rakhte hain)
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans # Zipkin ka address

# Logs mein Trace ID aur Span ID dikhane ke liye pattern set karna padta hai
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"